import { readFileSync, existsSync } from 'fs';
import { ChunkExtractor } from '@loadable/server';
import { statsPath } from './constants';

const extractor = new ChunkExtractor({
  // Read the stats file generated by webpack loadable plugin.
  // The file will not exist in develop stages.
  stats: existsSync(statsPath) ? JSON.parse(readFileSync(statsPath, 'utf8')) : {},
  entrypoints: [],
});

// extractor.collectChunks() will wrap the application in a ChunkExtractorManager
export const wrapRootElement = ({ element }) => extractor.collectChunks(element);

export const onRenderBody = ({ setPostBodyComponents, setHeadComponents }) => {
  // Set link rel="preload" tags in the head to start the request asap. This will NOT parse the assets fetched
  setHeadComponents(extractor.getLinkElements());

  // Set script and style tags at the end of the document to parse the assets.
  setPostBodyComponents([...extractor.getScriptElements(), ...extractor.getStyleElements()]);
};
